name: Autosave issue or comment to Markdown

on:
  issue_comment:
    types: [created]

permissions:
  contents: write

jobs:
  autosave-comment:
    if: contains(github.event.comment.body, '@autosave-in-new-file') || contains(github.event.comment.body, '@autosave-in-last-file')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare folder
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          FOLDER="docs/$ISSUE_NUMBER"
          mkdir -p "$FOLDER"
          echo "FOLDER=$FOLDER" >> $GITHUB_ENV

      - name: Determine filename prefix
        run: |
          FOLDER=$FOLDER
          # Get highest numeric prefix from existing files
          LAST_PREFIX=$(ls "$FOLDER"/[0-9]*-*.md 2>/dev/null | sed -E 's#.*/([0-9]+)-.*#\1#' | sort -n | tail -1)
          if [ -z "$LAST_PREFIX" ]; then
            LAST_PREFIX=0
          fi

          BODY="${{ github.event.comment.body }}"

          if [[ "$BODY" == *"@autosave-in-new-file"* ]]; then
            NEXT_PREFIX=$((LAST_PREFIX + 1))
          else
            NEXT_PREFIX=$LAST_PREFIX
          fi

          echo "NEXT_PREFIX=$NEXT_PREFIX" >> $GITHUB_ENV

      - name: Create Markdown file
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          FOLDER=$FOLDER
          PREFIX=$NEXT_PREFIX

          BODY="${{ github.event.comment.body }}"
          # Remove trigger commands from content
          BODY_CLEAN=$(echo "$BODY" | sed -E 's/@autosave-in-new-file//g; s/@autosave-in-last-file//g')

          FILENAME="$FOLDER/$PREFIX-autosaved-comment.md"

          echo "# ${{ github.event.issue.title }}" > "$FILENAME"
          echo "" >> "$FILENAME"
          echo "$BODY_CLEAN" >> "$FILENAME"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/${{ github.event.issue.number }}/*.md
          git commit -m "Autosave comment in issue #${{ github.event.issue.number }} to Markdown" || echo "No changes to commit"
          git push
