name: Autosave issue or comment to Markdown

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

permissions:
  contents: write

jobs:
  autosave:
    if: >
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@autosave-to-new-file') || contains(github.event.issue.body, '@autosave-to-last-file'))) ||
      (github.event_name == 'issue_comment' && (contains(github.event.comment.body, '@autosave-to-new-file') || contains(github.event.comment.body, '@autosave-to-last-file')))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare folder
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          FOLDER="docs/$ISSUE_NUMBER"
          mkdir -p "$FOLDER"
          echo "Using folder: $FOLDER"

      - name: Determine filename prefix and content
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          FOLDER="docs/$ISSUE_NUMBER"

          # Get highest numeric prefix from existing files
          LAST_PREFIX=$(ls "$FOLDER"/[0-9]*-*.md 2>/dev/null | sed -E 's#.*/([0-9]+)-.*#\1#' | sort -n | tail -1)
          if [ -z "$LAST_PREFIX" ]; then
            LAST_PREFIX=0
          fi

          # Determine body depending on event
          if [ "${GITHUB_EVENT_NAME}" == "issues" ]; then
            BODY="${{ github.event.issue.body }}"
            INCLUDE_TITLE="true"
          else
            BODY="${{ github.event.comment.body }}"
            INCLUDE_TITLE="false"
          fi

          # Determine trigger type
          if [[ "$BODY" == *"@autosave-to-new-file"* ]]; then
            NEXT_PREFIX=$((LAST_PREFIX + 1))
          else
            NEXT_PREFIX=$LAST_PREFIX
          fi

          # Remove trigger commands from content
          BODY_CLEAN=$(echo "$BODY" | sed -E 's/@autosave-to-new-file//g; s/@autosave-to-last-file//g')

          # Export as environment variables
          echo "NEXT_PREFIX=$NEXT_PREFIX" >> $GITHUB_ENV
          echo "BODY_CLEAN<<EOF" >> $GITHUB_ENV
          echo "$BODY_CLEAN" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "INCLUDE_TITLE=$INCLUDE_TITLE" >> $GITHUB_ENV

      - name: Create Markdown file
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          FOLDER="docs/$ISSUE_NUMBER"
          PREFIX=$NEXT_PREFIX
          FILENAME="$FOLDER/$PREFIX-autosaved-comment.md"

          # Start the file
          if [ "$INCLUDE_TITLE" = "true" ]; then
            echo "# ${{ github.event.issue.title }}" > "$FILENAME"
            echo "" >> "$FILENAME"
          else
            echo "" > "$FILENAME"
          fi

          # Append cleaned body safely
          printf "%s\n" "$BODY_CLEAN" >> "$FILENAME"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/${{ github.event.issue.number }}/*.md
          git commit -m "Autosave content in issue #${{ github.event.issue.number }} to Markdown" || echo "No changes to commit"
          git push
