name: Autosave issue or comment to Markdown

on:
  issues:
    types: [opened, edited]                # catch initial issue body
  issue_comment:
    types: [created, edited]               # catch comments

permissions:
  contents: write

jobs:
  autosave:
    if: >
      (github.event_name == 'issues' && contains(github.event.issue.body, '@autosave-in-new-file') ) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@autosave-in-last-file') ) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@autosave-in-new-file') ) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@autosave-in-last-file') )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare folder
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          FOLDER="docs/$ISSUE_NUMBER"
          mkdir -p "$FOLDER"
          echo "FOLDER=$FOLDER" >> $GITHUB_ENV

      - name: Determine filename prefix
        run: |
          FOLDER=$FOLDER
          # get highest numeric prefix from existing files
          LAST_PREFIX=$(ls "$FOLDER"/[0-9]*-*.md 2>/dev/null | sed -E 's#.*/([0-9]+)-.*#\1#' | sort -n | tail -1)
          if [ -z "$LAST_PREFIX" ]; then
            LAST_PREFIX=0
          fi

          # Select body depending on event
          if [ "${GITHUB_EVENT_NAME}" == "issues" ]; then
            BODY="${{ github.event.issue.body }}"
          else
            BODY="${{ github.event.comment.body }}"
          fi

          if [[ "$BODY" == *"@autosave-in-new-file"* ]]; then
            NEXT_PREFIX=$((LAST_PREFIX + 1))
          else
            NEXT_PREFIX=$LAST_PREFIX
          fi

          echo "NEXT_PREFIX=$NEXT_PREFIX" >> $GITHUB_ENV
          echo "BODY=$BODY" >> $GITHUB_ENV

      - name: Create Markdown file
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          FOLDER=$FOLDER
          PREFIX=$NEXT_PREFIX

          # Clean body: remove trigger commands
          BODY_CLEAN=$(echo "$BODY" | sed -E 's/@autosave-in-new-file//g; s/@autosave-in-last-file//g')

          FILENAME="$FOLDER/$PREFIX-autosaved-comment.md"

          # Include title only if event is the original issue creation
          if [ "${GITHUB_EVENT_NAME}" == "issues" ]; then
            echo "# ${{ github.event.issue.title }}" > "$FILENAME"
            echo "" >> "$FILENAME"
          else
            echo "" > "$FILENAME"   # start with empty file for comments
          fi

          # Append cleaned body
          echo "$BODY_CLEAN" >> "$FILENAME"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/${{ github.event.issue.number }}/*.md
          git commit -m "Autosave content in issue #${{ github.event.issue.number }} to Markdown" || echo "No changes to commit"
          git push
