name: Create subfolder and README.md in docs associated with a new issue

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write

jobs:
  create-project-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create docs folder and README
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}   # extract owner/repo
          # Make directory for the research project
          mkdir -p docs/$ISSUE_NUMBER

          # Create a README.md with issue reference
          echo "# Research Project $ISSUE_NUMBER:" > docs/$ISSUE_NUMBER/README.md
          echo "${{ github.event.issue.title }}" >> docs/$ISSUE_NUMBER/README.md
          echo "" >> docs/$ISSUE_NUMBER/README.md
          echo "👉 See original discussion in issue $REPO#$ISSUE_NUMBER" >> docs/$ISSUE_NUMBER/README.md

      - name: Commit and push changes
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/$ISSUE_NUMBER/README.md
          git commit -m "Add docs subfolder and docs/$ISSUE_NUMBER/README.md"
          git push
